apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-ch.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "hello-ch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-ch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image}}"
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: POSTGRES_SERVICE
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_SERVICE
                  name: hello-secret
            - name: POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB_NAME
                  name: hello-secret
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB_USER
                  name: hello-secret
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB_PASSWORD
                  name: hello-secret
